---
title: "Quadvariate Viz"
---

Use this file to generate a professional looking **quadvariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
```{r}
library(ggplot2)
library(ggridges)
```


```{r}
# Load data
elections_by_state <- read.csv("https://mac-stat.github.io/data/election_2020_by_state.csv")

# Check it out
head(elections_by_state )
```

```{r}

ggplot(elections_by_state, aes(x = dem_pct_20, y = repub_pct_20, color = winner_20, size = total_votes_20)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(values = c("red", "blue")) +  # Customize color if needed
  scale_size_continuous(name = "Per Capita Income") +
  labs(title = "2020 Election Results by State", 
       x = "Democratic Percentage (%)", 
       y = "Republican Percentage (%)") +
  theme_minimal() +
  theme(
    legend.position = "right",
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

  
  

```

