---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
```{r}
# Load required libraries
library(tidyverse)
library(openintro)
library(ggthemes)
library(RColorBrewer)
library(ggplot2)
library(leaflet)

```

```{r}
favorite_places <- tribble(
  ~place, ~long, ~lat, ~favorite,
  "Manzini", 31.3750815,-26.4976444, "no", 
  "Mbabane", 31.465866 , -26.522503, "yes",
  "Maputo", 32.56745, -25.966213, "no",
  "Cape Town", 18.4172197, -33.9288301, "no",
  "Durban", 31.009909, -29.861825, "yes",
  "Pretoria", 28.1879101, -25.7459277, "no",
  "Windhoek", 17.0454775, -22.5335601, "no",
  "Bulawayo", 28.5887063, -20.1560599, "no",
  "Maseru", 27.478222, -29.310054, "yes",
  "Gqeberha", 25.6186512, -33.9618359, "no"
  
  )

```

```{r}
# We can add colored circles instead of markers at each location
leaflet(data =favorite_places, options = leafletOptions(minZoom = 2, maxZoom = 30)) |> 
  addTiles() |> 
  addCircles(color = ~colorFactor(c("red", "green"), domain = favorite_places$favorite)(favorite), label = favorite_places$place) |>
  addLegend(position = "bottomright", 
            colors = c("green", "red"), 
            labels = c("Top 3 Favorite Places", "Other Favourite Places"), 
            title = "Legend")
```

