---
title: "Exam2"
format: html
---



```{r}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(sf)
```

```{r}
#Load data 
tuesdata<- tt_load("2020-02-18")
fc<- tuesdata$food_consumption 
```
```{r}
#Inspect data 
str(fc)

head(fc,22)

```
```{r}
distinct(fc,food_category)
```
- These values are too long

```{r}
fc <- fc |>
  mutate(food_category = fct_recode(food_category, 
                                    "lamb"= "Lamb & Goat", 
                                    "Diary" = "Milk - inc. cheese",
                                    "Wheat" = "Wheat and Wheat Products",
                                    "Nuts" = "Nuts inc. Peanut Butter")) 
```


```{r}
distinct(fc,food_category)
```

Research question: Which 5 countries consume the most food?

```{r}
fc |> group_by(country) |>
  summarise(Total_consumption = sum(consumption))|>
  arrange(desc(Total_consumption))|>
  head(5) |>
  ggplot(aes(x=country, fill = Total_consumption)) + geom_bar()
  
```
Research question: Which top 5 countries consume each food? 


```{r}
fc |> select(food_category, country,consumption) |>
  group_by(food_category) |>
  slice_max(order_by = consumption,n= 1)|>
  arrange(desc(consumption)) |>
  ggplot(aes(x= country, fill = consumption)) + geom_bar() + facet_wrap(~food_category)
  
```
Research question: What does the consumption of each food look like

```{r}
ne_countries(returnclass = "sf") |>
  select(name,geometry) |>
  mutate(name = ifelse(name == "united States of America", "USA", name)) |>
  mutate(name = ifelse(name == "Bosnia and Herz.", "Bosnia and Herzeggovonia", name)) |>
  mutate(name = ifelse(name == "Czechia", "Czech Republic", name)) |>
  mutate(name = ifelse(name == "Taiwan", "Taiwan. ROC", name)) |>
  left_join( fc |>
               select(-co2_emmission) |>
               group_by(food_category) |>
               mutate(consumption = (consumption -mean(consumption))/ sd(consumption)), 
             join_by(name == country)) |>
  pivot_wider(names_from = food_category, values_from = consumption) |>
  select(-"NA") |>
  pivot_longer(cols = c(-name, -geometry), 
               names_to = "food_category", 
               values_to = "consumption") |>
  ggplot() + geom_sf(aes(fill = consumption)) +
  facet_wrap(~food_category) + theme(legend.position = "bottom")
               
          
  
```

-This visualization can be enhanced by improving the use of visible color gradients
